{
 "title": "SSD  Health Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Model",
    "query": {
     "query": "query_result(sum(ssdhealth_power_on_hour{job=\"svc-app-infra-ssd-healthmonitoring\"}) by (device_model_no))"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "query_result(sum(ssdhealth_power_on_hour{job=\"svc-app-infra-ssd-healthmonitoring\"}) by (server_name))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Usage and Storage Capacity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ssdhealth_current_written{device_model_no=~\"$device\",server_name=~\"$server\"}",
     "legendFormat": " Current Written (GB): {{server_name}}, {{device_model_no}}, {{device_serial_no}}, {{device_path}}"
    },
    {
     "expr": "ssdhealth_total_life_written{device_model_no=~\"$device\",server_name=~\"$server\"}",
     "legendFormat": "Total Life Written (GB): {{server_name}}, {{device_model_no}}, {{device_serial_no}}, {{device_path}}"
    }
   ]
  },
  {
   "title": "Disk Uptime (Days)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "ssdhealth_power_on_hour{device_model_no=~\"$device\",server_name=~\"$server\"}",
     "legendFormat": "{{server_name}}, {{device_model_no}}, {{device_serial_no}}, {{device_path}}"
    }
   ]
  },
  {
   "title": "Estimated Remaining Lifespan (Days)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "ssdhealth_remaning_life{device_model_no=~\"$device\",server_name=~\"$server\"}",
     "legendFormat": "{{server_name}}, {{device_model_no}}, {{device_serial_no}}, {{device_path}}"
    }
   ]
  },
  {
   "title": "Disk Health Overview",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "ssdhealth_current_written{device_model_no=~\"$device\",server_name=~\"$server\"}",
     "legendFormat": "Total TBW"
    },
    {
     "expr": "ssdhealth_total_life_written{device_model_no=~\"$device\",server_name=~\"$server\"}",
     "legendFormat": "Total data written on Disk"
    },
    {
     "expr": "ssdhealth_remaning_life{device_model_no=~\"$device\",server_name=~\"$server\"}",
     "legendFormat": "Remain Days  "
    }
   ]
  }
 ]
}